rubatopy/rubato

- setup.cfg
> Bump dev version

- rubato/tests/vector_test.py
- rubato/utils/rb_math.py
- rubato/utils/vector.py
Created in place functions such as 
__imul__
and implemented them in vector tests.
Also checked that our rotations and angle handling works.
> Vector math upgrade

- docs/source/key-names.rst
- rubato/classes/camera.py
- rubato/classes/components/button.py
- rubato/classes/components/slider.py
- rubato/game.py
- rubato/utils/__init__.py
- rubato/utils/radio.py
- rubato/utils/rb_input.py
Takes the two first commits from mouse updated which are urgent proper fixes.
> Partial mouse update

- docs/source/key-names.rst
- rubato/utils/rb_input.py
Reordering key names as described in issue #167
> Reorder keynames

- docs/source/_templates/page.html
- setup.cfg
Resolves #170 
Adds a little icon in the footer that links to our Github.
Look like this:
> Make add github link in footer

- rubato/utils/display.py
- rubato/utils/rb_input.py
resolves #183
Switched our pointer statements to byref, so that it is more efficient.
> pointer to byref fix

- rubato/classes/components/animation.py
- rubato/classes/components/button.py
- rubato/classes/components/component.py
- rubato/classes/components/engine.py
- rubato/classes/components/hitbox.py
- rubato/classes/components/image.py
- rubato/classes/components/raster.py
- rubato/classes/components/rigidbody.py
- rubato/classes/components/slider.py
- rubato/classes/components/text.py
- rubato/classes/group.py
- rubato/game.py
- rubato/tests/group_test.py
- rubato/utils/__init__.py
- rubato/utils/display.py
- rubato/utils/draw.py
- rubato/utils/vector.py
> Overhauled draw order

- CHANGELOG.md
- demo/feature_test.py
- rubato/classes/components/image.py
Fix image resizing, scaling, and rotating
Fixes #162
> 162 problems with images

- rubato/game.py
- rubato/utils/__init__.py
- rubato/utils/debug.py
- rubato/utils/draw.py
- rubato/utils/radio.py
> clean game.py

- CHANGELOG.md
- demo/physics_demo.py
- rubato/classes/components/engine.py
- rubato/classes/components/rigidbody.py
> Original physics

- rubato/classes/components/animation.py
- rubato/classes/components/button.py
- rubato/classes/components/component.py
- rubato/classes/components/hitbox.py
- rubato/classes/components/image.py
- rubato/classes/components/raster.py
- rubato/classes/components/slider.py
- rubato/classes/components/text.py
- rubato/classes/game_object.py
- rubato/classes/group.py
- rubato/classes/scene.py
Actually do good clone functions
> Clone functions for all

- docs/source/conf.py
- docs/source/intro.rst
Adds the dropdown for linux command
> Fix the issue

- rubato/classes/group.py
- rubato/classes/qtree.py
- rubato/tests/group_test.py
now qtrees should recurse not quite as deep on average, probably improving performance by a couple frames a second
> trim qtree average depth

- CHANGELOG.md
- demo/pixel_mutation.py
- demo/platformer.py
- demo/quick_testing/noise_test.py
- rubato/__init__.py
- rubato/classes/scene.py
- rubato/game.py
- rubato/tests/init_test.py
> implement #239

- .github/workflows/auto_commenter.yml
auto commenter
*This message has been commented automatically because this PR was marked as ready for review.*
> Auto commenter

- demo/quick_testing/feature_test.py
- rubato/__init__.py
- rubato/utils/display.py
> Full Screen functionality

- CHANGELOG.md
- demo/camera_demo.py
- rubato/misc.py
- rubato/utils/camera.py
- rubato/utils/rb_input.py
> add world_mouse

- CHANGELOG.md
- demo/custom_components.py
- demo/noise_demo.py
- demo/physics_demo.py
- demo/pixel_mutation.py
- demo/platformer.py
- demo/quick_testing/noise_test.py
- demo/sound_demo.py
- demo/spaceships.py
- rubato/__init__.py
- rubato/struct/gameobject/game_object.py
- rubato/struct/gameobject/physics/hitbox.py
- rubato/struct/gameobject/physics/rigidbody.py
- rubato/struct/gameobject/raster.py
- rubato/struct/gameobject/sprites/animation.py
- rubato/struct/gameobject/sprites/image.py
- rubato/struct/gameobject/ui/button.py
- rubato/struct/gameobject/ui/slider.py
- rubato/struct/gameobject/ui/text.py
- rubato/struct/scene.py
- rubato/struct/scene_manager.py
- rubato/utils/radio.py
- tests/conftest.py
- tests/init_test.py
Reorders parameters
Fixes #224 
@tsedan and @mrElnekave please both approve before merging.
> reorder everything

- rubato/__init__.py
- rubato/game.py
- rubato/struct/gameobject/game_object.py
- rubato/struct/scene.py
- rubato/struct/scene_manager.py
- rubato/utils/__init__.py
- rubato/utils/draw.py
- rubato/utils/sprite.py
thank the lord it was easier than i thought it would be
> Fix import issues

- rubato/game.py
- rubato/utils/display.py
- rubato/utils/radio.py
> slight optimizations

- CHANGELOG.md
- docs/source/api.rst
- rubato/struct/__init__.py
- rubato/struct/gameobject/sprites/animation.py
- rubato/struct/gameobject/sprites/image.py
- rubato/struct/gameobject/sprites/spritesheet.py
- rubato/struct/sprite.py
- rubato/utils/__init__.py
- rubato/utils/draw.py
Closes #260 .
Note that the sprite.py file was moved from utils into struct. @tinmarr please update the docs to not break :)
> Sprite zooming

- rubato/utils/display.py
> no need to specify texture size

- CHANGELOG.md
- demo/custom_components.py
- demo/noise_demo.py
- demo/pixel_mutation.py
- demo/quick_testing/noise_test.py
- demo/sound_demo.py
- demo/spaceships.py
- rubato/__init__.py
- rubato/game.py
- rubato/struct/scene.py
- tests/conftest.py
- tests/init_test.py
quick change for window_size rename. If you want to rename anything else too, do it here.
> undoing window_size

- .github/workflows/deployment.yml
- .github/workflows/nightly.yml
- setup.cfg
- setup.py
> Fancy deployment script

- rubato/game.py
- rubato/utils/draw.py
- rubato/utils/radio.py
cleaned up some internal functionality
> not asyncio testfix

- .github/workflows/docs.yml
- .vscode/settings.json
> Docs build test

- demo/physics_demo.py
- demo/platformer.py
- demo/quick_testing/UI_test.py
- demo/quick_testing/feature_test.py
- demo/quick_testing/try_new_defaults.py
- demo/test/demo.py
- rubato/struct/gameobject/physics/hitbox.py
- rubato/struct/gameobject/ui/text.py
- rubato/utils/color.py
- rubato/utils/vector.py
- tests/init_test.py
> make Cython build properly

- CHANGELOG.md
- demo/platformer.py
- rubato/game.py
- rubato/utils/display.py
- rubato/utils/radio.py
- rubato/utils/rb_input.py
closes #228 
The tests will fail on this pr, and it's because of @tinmarr pushing broken code to remove metaclasses branch without fixing tests.
Nothing fundamental has changed so i think we can assume tests will pass on this for now. @tinmarr just do a sanity check on the code and we will merge into remove-metaclasses (not main because tests fail)
> Controller support

- CHANGELOG.md
- rubato/__init__.py
- rubato/game.py
- rubato/utils/display.py
> Window show + hide

- rubato/struct/gameobject/game_object.py
> Remove by ref

- rubato/struct/gameobject/particles/system.py
- rubato/utils/color.py
- rubato/utils/radio.py
- rubato/utils/rb_time.py
- tests/color_test.py
> Stupid changes

- CHANGELOG.md
- Makefile
- demo/events_demo.py
- demo/offset_demo.py
- docs/source/events.rst
- rubato/utils/color.py
- rubato/utils/radio.py
- rubato/utils/rb_time.py
- tests/game_test.py
> event tweaks

- .github/workflows/tests.yml
- CHANGELOG.md
- b
- demo/camera_demo.py
- demo/memory_test.py
- rubato/struct/gameobject/game_object.py
- rubato/struct/gameobject/particles/system.py
- rubato/struct/gameobject/physics/hitbox.py
- rubato/struct/gameobject/sprites/animation.py
- rubato/struct/gameobject/sprites/raster.py
- rubato/struct/gameobject/ui/text.py
- rubato/utils/draw.py
- setup.cfg
- tests/game_test.py
> camera parameters go brr

- CHANGELOG.md
- CONTRIBUTING.md
- demo/asteroids.py
- demo/draw_demo.py
- demo/memory_test.py
- demo/platformer.py
- demo/test/feature_test.py
- demo/tetris.py
- demo/time_demo.py
- rubato/struct/gameobject/sprites/animation.py
- rubato/utils/__init__.py
- rubato/utils/rb_time.py
These are the 2 main things i wanted during the game jam
The scheduled task test is in `feature_test.py`
And to test the animation alpha just add `p_animation.alpha = 128` near the bottom of `platformer.py` 
> scheduled task improvements and animation alpha

- rubato/struct/gameobject/ui/text.py
- rubato/struct/scene.py
- rubato/utils/rendering/camera.py
> add uptodate in Text component

- CHANGELOG.md
- demo/asteroids.py
- demo/draw_demo.py
- demo/memory_test.py
- demo/tetris.py
- demo/time_demo.py
- rubato/__init__.py
- rubato/game.py
- rubato/utils/radio/events.py
- rubato/utils/radio/radio.py
- rubato/utils/rb_time.py
- rubato/utils/rendering/draw.py
- tests/game_test.py
- tests/init_test.py
- tests/utils/hardware/input_test.py
> Use only seconds externally

- CHANGELOG.md
- demo/noise_demo.py
- rubato/utils/hardware/display.py
> Add maximize window

- rubato/c_src/cdraw.cpp
we dont like function overloading and also reorganized the order of the functions
> Reorganize cdraw

- CONTRIBUTING.md
- README.md
Introducing the new release date from a new contributor.
> New release date.

- .vscode/settings.json
- CHANGELOG.md
- b
- rubato/__init__.py
- rubato/__pyinstaller/hook-rubato.py
- rubato/game.py
- setup.cfg
Fixes #389 
Fixes #434 
-   Bug fix (non-breaking change which fixes an issue)
- Run `python -m build` to get a wheel located in the dist folder
- In a different virtual environment and outside of the rubato repo, install rubato from that wheel with:
```
pip install path/to/rubato.whl
```
- Try bundling a rubato project
> fix pyinstaller

- CHANGELOG.md
- rubato/game.py
LIttle flush fixes.
fixes #389
> flush fixes

- CHANGELOG.md
- demo/physics_demo.py
- rubato/structure/gameobject/physics/engine.py
- rubato/structure/gameobject/physics/hitbox.py
> Should collide
